// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "avito-intership-2025/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PrProvider is an autogenerated mock type for the PrProvider type
type PrProvider struct {
	mock.Mock
}

// DeleteReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *PrProvider) DeleteReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPrReviewers provides a mock function with given fields: ctx, prID
func (_m *PrProvider) GetPrReviewers(ctx context.Context, prID string) ([]string, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrReviewers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserReviews provides a mock function with given fields: ctx, userID
func (_m *PrProvider) GetUserReviews(ctx context.Context, userID string) ([]*models.PullRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviews")
	}

	var r0 []*models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID, newUserID
func (_m *PrProvider) ReassignReviewer(ctx context.Context, prID string, oldUserID string, newUserID string) error {
	ret := _m.Called(ctx, prID, oldUserID, newUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldUserID, newUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPrProvider creates a new instance of PrProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrProvider {
	mock := &PrProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
