// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReviewerProvider is an autogenerated mock type for the ReviewerProvider type
type ReviewerProvider struct {
	mock.Mock
}

// AssignReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *ReviewerProvider) AssignReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReviewer provides a mock function with given fields: ctx, prID, userID
func (_m *ReviewerProvider) DeleteReviewer(ctx context.Context, prID string, userID string) error {
	ret := _m.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPrReviewers provides a mock function with given fields: ctx, prID
func (_m *ReviewerProvider) GetPrReviewers(ctx context.Context, prID string) ([]string, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrReviewers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID, newUserID
func (_m *ReviewerProvider) ReassignReviewer(ctx context.Context, prID string, oldUserID string, newUserID string) error {
	ret := _m.Called(ctx, prID, oldUserID, newUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldUserID, newUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewerProvider creates a new instance of ReviewerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewerProvider {
	mock := &ReviewerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
