// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "avito-intership-2025/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamProvider is an autogenerated mock type for the TeamProvider type
type TeamProvider struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, teamName
func (_m *TeamProvider) Create(ctx context.Context, teamName string) (int, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeamName provides a mock function with given fields: ctx, teamName
func (_m *TeamProvider) GetByTeamName(ctx context.Context, teamName string) (*models.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamName")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamProvider creates a new instance of TeamProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamProvider {
	mock := &TeamProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
