// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamIDProvider is an autogenerated mock type for the TeamIDProvider type
type TeamIDProvider struct {
	mock.Mock
}

// GetTeamNameByID provides a mock function with given fields: ctx, teamID
func (_m *TeamIDProvider) GetTeamNameByID(ctx context.Context, teamID int) (string, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamNameByID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamIDProvider creates a new instance of TeamIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamIDProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamIDProvider {
	mock := &TeamIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
