// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "avito-intership-2025/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserChanger is an autogenerated mock type for the UserChanger type
type UserChanger struct {
	mock.Mock
}

// GetById provides a mock function with given fields: ctx, userID
func (_m *UserChanger) GetById(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetIsActive provides a mock function with given fields: ctx, userID, isActive
func (_m *UserChanger) SetIsActive(ctx context.Context, userID string, isActive bool) error {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserChanger creates a new instance of UserChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserChanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserChanger {
	mock := &UserChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
