// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	api "avito-intership-2025/internal/http/api"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamService is an autogenerated mock type for the MockTeamService type
type MockTeamService struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, teamName, users
func (_m *MockTeamService) Add(ctx context.Context, teamName string, users []api.TeamMember) (*api.TeamSchema, error) {
	ret := _m.Called(ctx, teamName, users)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *api.TeamSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []api.TeamMember) (*api.TeamSchema, error)); ok {
		return rf(ctx, teamName, users)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []api.TeamMember) *api.TeamSchema); ok {
		r0 = rf(ctx, teamName, users)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.TeamSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []api.TeamMember) error); ok {
		r1 = rf(ctx, teamName, users)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, teamName
func (_m *MockTeamService) Get(ctx context.Context, teamName string) (*api.TeamSchema, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *api.TeamSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.TeamSchema, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.TeamSchema); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.TeamSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
