// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	api "avito-intership-2025/internal/http/api"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPrService is an autogenerated mock type for the MockPrService type
type MockPrService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, prID, prName, authorId
func (_m *MockPrService) Create(ctx context.Context, prID string, prName string, authorId string) (*api.PullRequestSchema, error) {
	ret := _m.Called(ctx, prID, prName, authorId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *api.PullRequestSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*api.PullRequestSchema, error)); ok {
		return rf(ctx, prID, prName, authorId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *api.PullRequestSchema); ok {
		r0 = rf(ctx, prID, prName, authorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PullRequestSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, prName, authorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Merge provides a mock function with given fields: ctx, prID
func (_m *MockPrService) Merge(ctx context.Context, prID string) (*api.PullRequestSchema, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *api.PullRequestSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.PullRequestSchema, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.PullRequestSchema); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PullRequestSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reassign provides a mock function with given fields: ctx, prID, oldRev
func (_m *MockPrService) Reassign(ctx context.Context, prID string, oldRev string) (*api.ReassignResponse, error) {
	ret := _m.Called(ctx, prID, oldRev)

	if len(ret) == 0 {
		panic("no return value specified for Reassign")
	}

	var r0 *api.ReassignResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*api.ReassignResponse, error)); ok {
		return rf(ctx, prID, oldRev)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *api.ReassignResponse); ok {
		r0 = rf(ctx, prID, oldRev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ReassignResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prID, oldRev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPrService creates a new instance of MockPrService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrService {
	mock := &MockPrService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
