// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	api "avito-intership-2025/internal/http/api"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the MockUserService type
type MockUserService struct {
	mock.Mock
}

// GetReview provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetReview(ctx context.Context, userID string) (*api.GetReviewResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetReview")
	}

	var r0 *api.GetReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.GetReviewResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.GetReviewResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetReviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetIsActive provides a mock function with given fields: ctx, userID, isActive
func (_m *MockUserService) SetIsActive(ctx context.Context, userID string, isActive bool) (*api.UserSchema, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 *api.UserSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*api.UserSchema, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *api.UserSchema); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.UserSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
