// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	api "avito-intership-2025/internal/http/api"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStatsService is an autogenerated mock type for the MockStatsService type
type MockStatsService struct {
	mock.Mock
}

// GetStatistics provides a mock function with given fields: ctx, sort
func (_m *MockStatsService) GetStatistics(ctx context.Context, sort string) (*api.StatsResponse, error) {
	ret := _m.Called(ctx, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 api.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.StatsResponse, error)); ok {
		return rf(ctx, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) api.StatsResponse); ok {
		r0 = rf(ctx, sort)
	} else {
		r0 = ret.Get(0).(api.StatsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sort)
	} else {
		r1 = ret.Error(1)
	}

	return &r0, r1
}

// NewMockStatsService creates a new instance of MockStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsService {
	mock := &MockStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
